[package]
name = "caret"
version = "0.2.0"
edition = "2024"
rust-version = "1.92"
license = "GPL-3.0-or-later"
description = "A GPU-rendered terminal for GTK 4 and libadwaita"
repository = "https://github.com/sachesi/caret"
readme = "README.md"

[[bin]]
name = "caret"
path = "src/bin/caret.rs"

[dependencies]
gtk4 = { version = "0.11", features = ["v4_22"] }
libadwaita = { version = "0.9", features = ["v1_9"] }
gio = { version = "0.22", features = ["v2_80"] }
pangocairo = "0.22"
alacritty_terminal = "0.26"
glow = "0.18"
libloading = "0.9"
async-channel = "2"
gettext-rs = { version = "0.8", features = ["gettext-system"] }
libc = "0.2"
polling = "3"

[build-dependencies]
glib-build-tools = "0.22"

[profile.release]
lto = "thin"
codegen-units = 1
